AS twitter request
ecoledesdonnees/site pull request #24
Opened 2017-04-06 11:07 UTC by Agathesev

Display none sur .interact (lien d’action twitter)

2017-04-06 11:17 UTC, cecilaki requested changes
Je m'interroge sur le .TimePosted en fait, il apparait dans le site original et il m'apparait aussi comme une information importante, du coup je ne le mettrai pas en display:none. Mais je n'arrive pas à voir l'état actuel des choses puisque je n'arrive pas à afficher le flux twitter sur mon navigateur. Je m'en remets donc à ton appréciation à savoir si la date du tweet posté apparait déjà ou pas.

2017-04-06 15:03 UTC, Agathesev commented
![edd - tweet - http___127 0 0 1_4000_](https://cloud.githubusercontent.com/assets/4086067/24761135/d40d0378-1aea-11e7-8046-7fdaf95e6f66.png)

Screenshot de la section twitter.

Question 1 : Est-ce que cette section s'affiche bien chez vous ?
Question 2 : Est-ce bien l'attendu ?

2017-04-07 11:08 UTC, cecilaki commented
@pzwsk @clombion vous voyez le flux twitter s'afficher sur tous vos navigateurs ?

@Agathesev oui à priori c'est bien ça qu'on attend. Tu peux commit le code.

2017-04-10 11:44 UTC, cecilaki commented
Coucou @Agathesev tu as revert le code des 3 colonnes pour le placer ailleurs ?

2017-04-10 11:54 UTC, Agathesev commented
@cecilaki ben oui, je voulais te faire une pullrequest spéciale, mais pas moyen...

2017-04-10 12:05 UTC, cecilaki commented
Ah bon mais c'est bizarre ça. Pays moyen de quoi du coup ?

2017-04-10 12:41 UTC, merged